In [1]:
import numpy as np

In [ ]:
#1. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [2]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [1]:
#2. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
#Original array:
# [[0 1]
#  [2 3]]
# Sum of all elements:
# 6
# Sum of each column:
# [2 4]
# Sum of each row:
# [1 5]

In [12]:
n1 =  np.arange(4).reshape(2,2)
print(np.sum(n1))
print(np.array([np.sum(np.hsplit(n1,2)[0]),np.sum(np.hsplit(n1,2)[1])]))
print(np.array([np.sum(np.vsplit(n1,2)[0]),np.sum(np.vsplit(n1,2)[1])]))

6
[2 4]
[1 5]


In [3]:
#3.make a 4x5 array containing numbers from 34-54 and then make it a 1D array
#input:[[34 35 36 37 38]
#  [39 40 41 42 43]
#  [44 45 46 47 48]
#  [49 50 51 52 53]]
# output:[34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53]

In [16]:
n = np.array([[34,35,36,37,38],
              [39,40,41,42,43],
              [44,45,46,47,48],
              [49,50,51,52,53]])
np.ravel(n)

array([34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53])

In [17]:
#4.Using the below given Matrix, generate the output for the below questions.

In [18]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
#4a)Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique
#4b)Retrieve the value 55 from the above matrix using index & selection technique
#4c)Retrieve the values from the 3rd column in the above matrix
#4d)Retrieve the values from the 4th row in the above matrix
#4e)Retrieve values from the 2nd & 4th rows in the above matrix

In [23]:
print(simple_matrix[-2:,:3])
print(simple_matrix[5,4])
print(simple_matrix[:,2])
print(simple_matrix[3])
print(simple_matrix[[1,3]])

[[81 82 83]
 [91 92 93]]
55
[ 3 13 23 33 43 53 63 73 83 93]
[31 32 33 34 35 36 37 38 39 40]
[[11 12 13 14 15 16 17 18 19 20]
 [31 32 33 34 35 36 37 38 39 40]]


In [49]:
#5.Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. Go to the editor
# Expected Output:
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70, 90]
# Set difference between two arrays:
# [ 0 20 60 80]

In [25]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = [10, 30, 40, 50, 70]
np.setdiff1d(array2,array1)

array([30, 50, 70])

In [52]:
#6. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays. Go to the editor
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70]
# Unique values that are in only one (not both) of the input arrays:
# [ 0 20 30 50 60 70 80]

In [26]:
np.setxor1d(array1,array2)

array([ 0, 20, 30, 50, 60, 70, 80])

In [ ]:
#7. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays. Go to the editor
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70]
# Unique sorted array of values that are in either of the two input arrays:
# [ 0 10 20 30 40 50 60 70 80]

In [27]:
np.union1d(array1,array2)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [59]:
#8.Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 
#elements in the original order.
# Expected Output:
# Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
# After splitting:
# [array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

In [32]:
n = np.arange(1,15)
np.hsplit(n,[2,6])

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]

In [ ]:
#9.Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis. 
# Sample array :
# [[ 0 1 2 3]
# ........
# [12 13 14 15]]
# Expected Output:
# [array([[ 0, 1],
# [ 4, 5],
# [ 8, 9],
# [12, 13]]), array([[ 2, 3],
# [ 6, 7],
# [10, 11],
# [14, 15]]), array([], shape=(4, 0), dtype=int64)]

In [34]:
n = np.arange(16).reshape(4,4)
np.hsplit(n,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
#10.Write a NumPy program to split a given array into multiple sub-arrays vertically (row-wise). Go to the editor
# Sample Output:
# Original arrays:
# [[ 0. 1. 2. 3.]
# .............
# [12. 13. 14. 15.]]
# Split an array into multiple sub-arrays vertically:
# [array([[0., 1., 2., 3.],
# [4., 5., 6., 7.]]), array([[ 8., 9., 10., 11.],
# [12., 13., 14., 15.]])]

In [35]:
np.vsplit(n,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [68]:
#11.Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3). 
#The p variable has a shape of (3, 3), while q only has a shape of 3(1d).

# Sample Output:
# Original arrays:
# Array-1
# [[0 0 0]
# [1 2 3]
# [4 5 6]]
# Array-2
# [10 11 12]
# New Array:
# [[10 11 12]
# [11 13 15]
# [14 16 18]]

In [36]:
p = np.array([[0, 0, 0],
              [1, 2, 3],
              [4, 5, 6]])
q = np.array([10,11,12])
print(p+q)

[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [37]:
##12.Write a NumPy program to broadcast on different shapes of arrays where a(,3)(1column:2d) + b(3)(1d).

In [ ]:
#Sample Output:
# Original arrays:
# Array-1
# [[ 0]
# [10]
# [20]]
# Array-2
# [10 11 12]
# New Array:
# [[10 11 12]
# [20 21 22]
# [30 31 32]]

In [38]:
p = np.array([[0],
             [10],
             [20]])
q = np.array([10,11,12])
print(p+q)

[[10 11 12]
 [20 21 22]
 [30 31 32]]


In [6]:
#13.Multiply a 5x3 matrix by a 3x2 matrix

In [39]:
n1 = np.arange(15).reshape(5,3)
n2 = np.arange(6).reshape(3,2)
n1.dot(n2)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [ ]:
#14. Calculate the following values for the given matrix
# a) Calculate sum of all the values in the matrix

# b) Calculate standard deviation of all the values in the matrix

# c) Calculate the variance of all values in the matrix

# d) Calculate the mean of all values in the matrix

# e) Retrieve the largest number from the matrix

# f) Retrieve the smallest number from the matrix


In [41]:
n = np.array([10,11,12,13,14,15,16])
print(np.sum(n))
print(np.std(n))
print(np.mean(n))
print(np.amax(n))
print(np.amin(n))

91
2.0
13.0
16
10


In [ ]:
# 15.Create an array of integers starting from 21 until 31 and name it as array1
# Create an array of integers starting from 11 until 21 and name it array2
# Calculate the difference between array1 and array2

In [43]:
array1 = np.arange(21,32)
array2 = np.arange(11,22)
array1 - array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [83]:
#16. Use NumPy to generate a random set of 10 numbers between 0 and 1
# Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [47]:
np.random.seed(20)
n = np.random.rand(10)
n>0.2

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
       False])

In [85]:
#17.Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [49]:
np.random.randn(10).reshape(5,2)

array([[-1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255],
       [ 1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279],
       [ 1.12013226,  1.33277821]])

In [87]:
#18. Create an array of 30 linearly spaced points between 0 and 100:

In [52]:
np.linspace(0,100,30,retstep=True)

(array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
         41.37931034,  44.82758621,  48.27586207,  51.72413793,
         55.17241379,  58.62068966,  62.06896552,  65.51724138,
         68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]), 3.4482758620689653)