In [1]:
import numpy as np

In [20]:
#NOTE:np.where() explained in day2 exercise solutions , Have a look at that before doing the below questions

In [1]:
#1.Get the positions where elements of a and b match

In [3]:
#2.From the array a, replace all values greater than 30 to 30 and less than 30 to 29.

In [4]:
#3.From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [5]:
#4.# Write a NumPy program to split a given array into multiple sub-arrays vertically (row-wise).
# Sample Output:
# Original arrays:
# [[ 0. 1. 2. 3.]
# .............
# [12. 13. 14. 15.]]
# Split an array into multiple sub-arrays vertically:
# [array([[0., 1., 2., 3.],
# [4., 5., 6., 7.]]), array([[ 8., 9., 10., 11.],
# [12., 13., 14., 15.]])]

In [6]:
#5.Normalize a 5x5 random matrix 

In [7]:
#6. #Given a 1D array, negate all elements which are between 3 and 8, in place.
#input: 0,1,2,3,4,5,6,7,8,9,10

In [9]:
#7.Consider two random array A and B, check if they are equal

IndexError: too many indices for array

In [10]:
#8. Create random vector of size 10 and replace the maximum value by 0

In [11]:
#9. # Create a 5x6 matrix with values ranging from 0 to 29 and retrieve the value intersecting at 2nd row and 3rd column

In [12]:
#10. Create a checkerboard 8x8 matrix using the tile function
#output:
# [[0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]
#  [0 1 0 1 0 1 0 1]
#  [1 0 1 0 1 0 1 0]]

In [11]:
np.tile([0,1],(8,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [15]:
#11. Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [8]:
n = np.arange(15)
c = np.where((n>3)&(n<8),n*-1,n)
c

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
#12. Create a vector of size 10 with values ranging from 0 to 1, both excluded  #hint:use linespace: endpoint

In [17]:
#13. Create a random vector of size 10 and sort it

In [9]:
np.sort([1,8,4,3,7,5,8])

array([1, 3, 4, 5, 7, 8, 8])

In [18]:
#14: Subtract the mean of each row of a matrix from every number

In [16]:
n = np.arange(15).reshape(3,5)
m = np.mean(n,axis=1)
print(m)
print(n)

[ 2.  7. 12.]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

In [19]:
#15. How to swap two rows of an array? 

In [17]:
a = np.array([[4,3,1], [5,7,0], [9,9,3], [8,2,4]])
a[[0,2]] = a[[2,0]]
a

array([[9, 9, 3],
       [5, 7, 0],
       [4, 3, 1],
       [8, 2, 4]])