In [1]:
import numpy as np

In [2]:
#1. Create an empty array of 20 0's and replace the 4th object with the number 5

In [5]:
a = np.zeros(20)
a[3] = 5

In [6]:
a

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
a = np.zeros(shape=(1,20))


In [8]:
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [11]:
a.shape

(1, 20)

In [12]:
a[0,3] = 5

In [13]:
a

array([[0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [15]:
#2.Create an array of 20 1's and store it as a variable named array_master. 
#Copy the same array into another variable named array_copy

In [17]:
array_master= np.ones(20)    #predefined function
array_copy= array_master   #shallow copy
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [18]:
array_master[3] = 5

In [19]:
array_master

array([1., 1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [20]:
array_copy

array([1., 1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [21]:
array_master= np.ones(20)    #predefined function
array_copy = array_master.copy()   #shallow copy
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [22]:
array_copy[3] = 5

In [23]:
array_copy

array([1., 1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [24]:
array_master

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [25]:
array_master[6] = 99

In [26]:
array_master

array([ 1.,  1.,  1.,  1.,  1.,  1., 99.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
array_copy

array([1., 1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [ ]:
#3. Create an array containing 30 1's and broadcast all the one's to the value 100

In [30]:
a = np.ones(30)  #1D array
print(a)
a[:]  = 100     

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [29]:
a

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

In [32]:
a = np.ones(30) + 99
a

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

In [33]:
a = np.ones(30) * 100
a

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100., 100., 100., 100.,
       100., 100., 100., 100., 100., 100., 100., 100.])

In [34]:
np.repeat(100,30)        

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [40]:
b = np.repeat(100,12) 

In [41]:
b.reshape(4,3)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [46]:
np.full(shape=(30),fill_value = 100)


array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [45]:
#4.Create an array of all even integers from 2 to 10 and name it a1
# Create an array of all even integers from 22 to 30 and name it a2

In [47]:
a1 = np.arange(2,11,2)    #stepsize = 2: even

a2 = np.arange(22,31,2)

print(a1)
print(a2)



[ 2  4  6  8 10]
[22 24 26 28 30]


In [48]:
#4a)Use the 2 arrays as rows and create a matrix [ Hint - Use stack function from numpy ](2,5)
#output: array([[ 2,  4,  6,  8, 10],
#               [22, 24, 26, 28, 30]])

In [50]:
c=np.vstack((a1,a2))
c

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [51]:
np.row_stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [53]:
np.stack((a1,a2),axis=0)     

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [54]:
#4.b)Use the 2 arrays as columns and create a matrix [ Hint - Use stack function from numpy ]

In [56]:
a3 = np.stack((a1,a2),axis=1)
a3

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [57]:
np.hstack((a1,a2))

array([ 2,  4,  6,  8, 10, 22, 24, 26, 28, 30])

In [58]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [62]:
c = np.vstack((a1))
print(c)
print(c.shape)
d = np.vstack((a2))
print(d)
e = np.hstack((c,d))
e

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]
(5, 1)
[[22]
 [24]
 [26]
 [28]
 [30]]


array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [63]:
#5.Create an identity matrix of shape 10x10 and replace the 0's with the value 21

In [64]:
f = np.identity(10)
f

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [72]:
f[f==0] = 21
f

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

In [73]:
arr = np.eye(10)

arr[arr == 0] = 21

arr

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

In [78]:
np.eye(10,k=0)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [75]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [79]:
#6. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [80]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])