In [2]:
import numpy as np

### First 3 are for day1 exercise solutions

In [ ]:
#1. how do I make a 1d array of 15 elements in a 2d array: all the ways

In [3]:
arr1 = np.random.randint(1,15,size=15)
arr1.shape

(15,)

In [4]:
arr1.reshape(-1,15)

array([[ 1,  7,  7, 12,  9,  5,  9,  1, 11,  9,  5,  3, 11,  6, 13]])

In [5]:
arr1.reshape(3,5)

array([[ 1,  7,  7, 12,  9],
       [ 5,  9,  1, 11,  9],
       [ 5,  3, 11,  6, 13]])

In [ ]:
#2. Create a 2d array with 1 on the border and 0 inside

In [6]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
Z = np.zeros((10,10))
Z[0,:] = 1
Z[:,0] = 1
Z[-1,:] = 1
Z[:,-1] = 1
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#3.Find non-zero elements from [1,2,0,0,4,0]
#Find indices of non-zero elements from [1,2,0,0,4,0]

In [18]:
nz = np.array([1,2,0,0,4,0])
nz[(nz>0)]

array([1, 2, 4])

In [19]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


### From here Day2 exercise solutions

In [ ]:
#1. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5

In [20]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [21]:
a=np.eye(5)
a[a==1]=[1,2,3,4,5]
print(a)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [1]:
#2. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.
#Original array:
# [[0 1]
#  [2 3]]
# Sum of all elements:
# 6
# Sum of each column:
# [2 4]
# Sum of each row:
# [1 5]

In [22]:
import numpy as np
x = np.array([[0,1],[2,3]])
print("Original array:")
print(x)
print("Sum of all elements:")
print(np.sum(x))
print("Sum of each column:")
print(np.sum(x, axis=0))
print("Sum of each row:")
print(np.sum(x, axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [3]:
#3.make a 4x5 array containing numbers from 34-54 and then make it a 1D array
#input:[[34 35 36 37 38]
#  [39 40 41 42 43]
#  [44 45 46 47 48]
#  [49 50 51 52 53]]
# output:[34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53]

In [23]:
a_2d = np.arange(34,54).reshape(4,5)
print(a_2d)
a_1d = a_2d.ravel()
print(a_1d)

[[34 35 36 37 38]
 [39 40 41 42 43]
 [44 45 46 47 48]
 [49 50 51 52 53]]
[34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [ ]:
#4.Using the below given Matrix, generate the output for the below questions.

In [25]:
simple_matrix = np.arange(1,101).reshape(10,10)
simple_matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
#4a)Retrieve the last 2 rows and first 3 column values of the above matrix using index & selection technique
#4b)Retrieve the value 55 from the above matrix using index & selection technique
#4c)Retrieve the values from the 3rd column in the above matrix
#4d)Retrieve the values from the 4th row in the above matrix
#4e)Retrieve values from the 2nd & 4th rows in the above matrix

In [26]:
#a)
simple_matrix[8:,0:3]

array([[81, 82, 83],
       [91, 92, 93]])

In [27]:
#b)
simple_matrix[5,4]

55

In [28]:
#c)
simple_matrix[:,2]

array([ 3, 13, 23, 33, 43, 53, 63, 73, 83, 93])

In [29]:
#d)
simple_matrix[3,:]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [30]:
#e)
simple_matrix[(1,3),:]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [49]:
#5.Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. Go to the editor
# Expected Output:
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70, 90]
# Set difference between two arrays:
# [ 0 20 60 80]

In [31]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [52]:
#6. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays. Go to the editor
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70]
# Unique values that are in only one (not both) of the input arrays:
# [ 0 20 30 50 60 70 80]

In [32]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values that are in only one (not both) of the input arrays:")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays:
[ 0 20 30 50 60 70 80]


In [ ]:
#7. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays. Go to the editor
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70]
# Unique sorted array of values that are in either of the two input arrays:
# [ 0 10 20 30 40 50 60 70 80]

In [33]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique sorted array of values that are in either of the two input arrays:")
print(np.union1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique sorted array of values that are in either of the two input arrays:
[ 0 10 20 30 40 50 60 70 80]


In [ ]:
#2.From the array a, replace all values greater than 30 to 30 and less than 30 to 29.

In [38]:
# np.where(condition, if true, if false)
#numpy.where(condition[, x, y]) function returns the indices of elements in an input array 
#where the given condition is satisfied.

In [44]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 
b = np.where(a<4) 
print(b) #00,01,02

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))


In [45]:
a[b]

array([1, 2, 3])

In [48]:
np.where(a<4,99,0)

array([[99, 99, 99],
       [ 0,  0,  0]])

In [4]:
import numpy as np
np.random.seed(100)
a = np.random.uniform(1,50, 20)
a

# Solution
print("Solution")
c1 = np.where(a > 30)
c2 = np.where(a < 10)
a[c1] = 30
a[c2] = 10

Solution


In [41]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(np.where(a < 10, 10, np.where(a > 30, 30, a)))

[27.62684215 14.64009987 21.80136195 30.         10.         10.
 30.         30.         10.         29.17957314 30.         11.25090398
 10.08108276 10.         11.76517714 30.         30.         10.
 30.         14.42961361]


In [59]:
#8.Write a NumPy program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 
#elements in the original order.
# Expected Output:
# Original array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]
# After splitting:
# [array([1, 2]), array([3, 4, 5, 6]), array([ 7, 8, 9, 10, 11, 12, 13, 14])]

In [50]:
import numpy as np
x = np.arange(1, 15)
print("Original array:",x)
print("After splitting:")
print(np.split(x, [2, 6]))
#   ary[:2]
#   ary[2:6]
#   ary[6:]

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting:
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [ ]:
#9.Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis. 
# Sample array :
# [[ 0 1 2 3]
# ........
# [12 13 14 15]]
# Expected Output:
# [array([[ 0, 1],
# [ 4, 5],
# [ 8, 9],
# [12, 13]]), array([[ 2, 3],
# [ 6, 7],
# [10, 11],
# [14, 15]]), array([], shape=(4, 0), dtype=int64)]

In [56]:
import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [ ]:
#10.Write a NumPy program to split a given array into multiple sub-arrays vertically (row-wise).
# Sample Output:
# Original arrays:
# [[ 0. 1. 2. 3.]
# .............
# [12. 13. 14. 15.]]
# Split an array into multiple sub-arrays vertically:
# [array([[0., 1., 2., 3.],
# [4., 5., 6., 7.]]), array([[ 8., 9., 10., 11.],
# [12., 13., 14., 15.]])]

In [52]:
import numpy as np
x = np.arange(16).reshape((4, 4))
print("Original array:",x)
print("After splitting horizontally:")
print(np.hsplit(x, [2, 6]))

Original array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [68]:
#11.Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3). 
#The p variable has a shape of (3, 3), while q only has a shape of 3(1d).

# Sample Output:
# Original arrays:
# Array-1
# [[0 0 0]
# [1 2 3]
# [4 5 6]]
# Array-2
# [10 11 12]
# New Array:
# [[10 11 12]
# [11 13 15]
# [14 16 18]]

In [55]:
import numpy as np    
p = np.array([[0, 0, 0],
              [1, 2, 3],
              [4, 5, 6]]) 
q= np.array([10, 11, 12]) 
print("Original arrays:")
print("Array-1")
print(p)
print("Array-2")
print(q)
print("\nNew Array:")
new_array1 = p + q 
print(new_array1)

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [69]:
##12.Write a NumPy program to broadcast on different shapes of arrays where a(,3)(1column:2d) + b(3)(1d).

In [ ]:
#Sample Output:
# Original arrays:
# Array-1
# [[ 0]
# [10]
# [20]]
# Array-2
# [10 11 12]
# New Array:
# [[10 11 12]
# [20 21 22]
# [30 31 32]]

In [57]:
import numpy as np    
p = np.array([[0], [10], [20]]) 
q= np.array([10, 11, 12]) 
print("Original arrays:")
print("Array-1")
print(p)
print("Array-2")
print(q)
print("\nNew Array:")
new_array1 = p + q 
print(new_array1)

Original arrays:
Array-1
[[ 0]
 [10]
 [20]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [20 21 22]
 [30 31 32]]


In [6]:
#13.Multiply a 5x3 matrix by a 3x2 matrix

In [58]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#14. Calculate the following values for the given matrix
# a) Calculate sum of all the values in the matrix

# b) Calculate standard deviation of all the values in the matrix

# c) Calculate the variance of all values in the matrix

# d) Calculate the mean of all values in the matrix

# e) Retrieve the largest number from the matrix

# f) Retrieve the smallest number from the matrix


In [59]:
#a)

print(simple_matrix.sum())

#b)
print(simple_matrix.std())

#c)
print(simple_matrix.var())

#d)
print(simple_matrix.mean())

#e)
print(simple_matrix.max())

#f)
print(simple_matrix.min())

5050
28.86607004772212
833.25
50.5
100
1


In [60]:
# 15.Create an array of integers starting from 21 until 31 and name it as array1
# Create an array of integers starting from 11 until 21 and name it array2
# Calculate the difference between array1 and array2

In [61]:
array1 = np.arange(21,32)

array2 = np.arange(11,22)

array1 - array2

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [83]:
#16. Use NumPy to generate a random set of 10 numbers between 0 and 1
# Display a boolean array output where all values > 0.2 are True, rest are marked as False

In [62]:
ar = np.random.rand(10)

ar>0.2

array([ True,  True,  True,  True, False,  True, False,  True,  True,
       False])

In [85]:
#17.Use NumPy to generate an array matrix of 5x2 random numbers sampled from a standard normal distribution

In [63]:
np.random.randn(5,2)

array([[ 1.61898166,  1.54160517],
       [-0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ],
       [ 0.73100034,  1.36155613],
       [-0.32623806,  0.05567601]])

In [87]:
#18. Create an array of 30 linearly spaced points between 0 and 100:

In [64]:
np.linspace(0,100,30)

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [3]:
a=np.arange(15).reshape(3,5)
print(a.dtype.name)

int32


In [8]:
import numpy as np
z=np.arange(4)
(z>0) & (z<5)

array([False,  True,  True,  True])

In [9]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [10]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [12]:
a=np.random.rand(1,1,2)
a

array([[[0.16206328, 0.14055687]]])

In [13]:
np.array([[1, 2], [3, 4.0]])

array([[1., 2.],
       [3., 4.]])

In [19]:
np.array([1, 2, 3], ndmin=3)

array([[[1, 2, 3]]])

In [17]:
a=np.arange(0,0,2)
a

array([], dtype=int32)

In [18]:
a=np.arange(15).reshape(3,5)
print(a.dtype.name)

int32
