In [1]:
import numpy as np

In [2]:
mylist = [111,222,333,444,555]

In [3]:
n1 = np.array(mylist)
n1

array([111, 222, 333, 444, 555])

In [5]:
n1.shape  # element in each axis

(5,)

In [6]:
n1.ndim   # no of dimension

1

In [8]:
n1.size   # total no of elements in the array

5

In [16]:
n1.itemsize   # size in byte occupied by  each element

4

In [10]:
n1.dtype

dtype('int32')

In [12]:
n1.size * n1.itemsize

20

In [13]:
n2 = np.array(mylist,dtype = np.int64)
n2.size

5

In [15]:
n2.itemsize

8

In [18]:
n5a = np.arange(5)
n5a

array([0, 1, 2, 3, 4])

In [19]:
n5b = np.arange(5,10)
n5b

array([5, 6, 7, 8, 9])

In [20]:
n5a + n5b

array([ 5,  7,  9, 11, 13])

In [21]:
n5a - n5b

array([-5, -5, -5, -5, -5])

In [22]:
n5a * n5b

array([ 0,  6, 14, 24, 36])

In [23]:
n5a ** n5b

array([     0,      1,    128,   6561, 262144], dtype=int32)

In [28]:
n25 = np.random.randint(0,100,25)
n25

array([60, 78, 25, 14, 24, 75, 92, 90, 85,  1, 80, 41, 62, 81,  9,  2, 69,
       97, 81, 94, 14, 41, 24,  2,  1])

In [29]:
n25.size

25

In [30]:
n25.shape

(25,)

In [33]:
n10 = np.random.randint(1600,1700,100)

In [34]:
n10

array([1675, 1661, 1608, 1618, 1650, 1641, 1617, 1688, 1650, 1648, 1679,
       1611, 1627, 1628, 1651, 1697, 1689, 1662, 1604, 1610, 1605, 1692,
       1652, 1696, 1600, 1680, 1614, 1639, 1684, 1633, 1618, 1629, 1663,
       1649, 1648, 1631, 1633, 1644, 1691, 1653, 1626, 1642, 1657, 1662,
       1688, 1697, 1679, 1673, 1692, 1602, 1636, 1623, 1683, 1669, 1623,
       1697, 1645, 1608, 1667, 1657, 1626, 1663, 1686, 1663, 1665, 1617,
       1656, 1679, 1613, 1648, 1633, 1678, 1621, 1621, 1673, 1643, 1670,
       1638, 1612, 1638, 1600, 1613, 1620, 1624, 1670, 1602, 1647, 1650,
       1652, 1607, 1682, 1626, 1682, 1664, 1668, 1637, 1608, 1689, 1671,
       1675])

In [35]:
print(n10.size)
print(np.unique(n10).size)

100
66


In [38]:
np.random.seed(10)
n25 = np.random.randint(0,100,25)
n25

array([ 9, 15, 64, 28, 89, 93, 29,  8, 73,  0, 40, 36, 16, 11, 54, 88, 62,
       33, 72, 78, 49, 51, 54, 77, 69])

# Access

In [42]:
np.random.seed(10)
n20 = np.random.randint(50,100,20)
n20

array([59, 86, 65, 50, 99, 78, 75, 79, 98, 79, 99, 58, 59, 50, 92, 90, 86,
       66, 86, 97])

In [43]:
n20[3]

50

In [44]:
n20[[3,7,2,5,18,12,14]]

array([50, 79, 65, 78, 86, 59, 92])

In [45]:
n20[2:6]

array([65, 50, 99, 78])

In [50]:
mask = n20 > 75
print(mask)
print(type(mask))
mask.size

[False  True False False  True  True False  True  True  True  True False
 False False  True  True  True False  True  True]
<class 'numpy.ndarray'>


20

In [51]:
n20[mask]

array([86, 99, 78, 79, 98, 79, 99, 92, 90, 86, 86, 97])

In [52]:
n20[n20>75]  # conditional accesing

array([86, 99, 78, 79, 98, 79, 99, 92, 90, 86, 86, 97])

In [54]:
n20[(n20>=60) & (n20%2==0)]

array([86, 78, 98, 92, 90, 86, 66, 86])

In [55]:
n20[3:6] = 666
n20

array([ 59,  86,  65, 666, 666, 666,  75,  79,  98,  79,  99,  58,  59,
        50,  92,  90,  86,  66,  86,  97])

In [56]:
n20[[3,7,2,5,18,12,14]] = 999
n20

array([ 59,  86, 999, 999, 666, 999,  75, 999,  98,  79,  99,  58, 999,
        50, 999,  90,  86,  66, 999,  97])

In [57]:
n20[n20>75]

array([ 86, 999, 999, 666, 999, 999,  98,  79,  99, 999, 999,  90,  86,
       999,  97])

In [58]:
n20[n20>75] = 99
n20

array([59, 99, 99, 99, 99, 99, 75, 99, 99, 99, 99, 58, 99, 50, 99, 99, 99,
       66, 99, 99])

# 2D Array

In [59]:
my_list_3_4 = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [60]:
n34 = np.array(my_list_3_4)
n34

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
n34.ndim

2

In [62]:
n34.size

12

In [63]:
n34.shape

(3, 4)

In [68]:
n1_4 = np.array([1,2,3,4])
n1_4

array([1, 2, 3, 4])

In [69]:
n1_4.shape

(4,)

In [70]:
n1_4.ndim

1

In [72]:
n34 = np.arange(12)
n34

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
n34.shape

(12,)

In [74]:
n34 = np.arange(12).reshape(3,4)
n34

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
n34.shape

(3, 4)

In [77]:
n34 = np.arange(12).reshape(-1,4)
print(n34)
print(n34.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [79]:
n62 = n34.reshape(6,2)
n62

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [83]:
n64 = np.arange(24).reshape(6,4)
n64

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [86]:
np.random.seed(10)
n64 = np.random.randint(100,200,(6,4))
n64

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136],
       [116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [88]:
np.random.seed(10)
n64 = np.random.randint(100,200,24).reshape(6,-1)
n64

array([[109, 115, 164, 128],
       [189, 193, 129, 108],
       [173, 100, 140, 136],
       [116, 111, 154, 188],
       [162, 133, 172, 178],
       [149, 151, 154, 177]])

In [91]:
np.random.seed(10)
n34a = np.random.randint(10,30,(3,4))
n34b = np.random.randint(30,50,(3,4))
print(n34a)
print(n34b)


[[19 14 25 10]
 [27 26 27 18]
 [19 10 20 18]]
[[34 49 46 34]
 [45 41 41 31]
 [38 34 44 47]]


In [92]:
n34a + n34b

array([[53, 63, 71, 44],
       [72, 67, 68, 49],
       [57, 44, 64, 65]])

In [93]:
n34a.dot(n34b)

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [95]:
n43b = n34b.T
n43b

array([[34, 45, 38],
       [49, 41, 34],
       [46, 41, 44],
       [34, 31, 47]])

In [96]:
n34a.dot(n43b)

array([[2822, 2764, 2768],
       [4046, 3946, 3944],
       [2668, 2643, 2788]])

In [102]:
i4 = np.eye(4)
i4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [109]:
i3 = np.identity(3)
i3

TypeError: identity() got an unexpected keyword argument 'k'

In [105]:
i4 = np.eye(4,k=0)
i4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [106]:
i4 = np.eye(4,k=1)
i4

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [107]:
i4 = np.eye(4,k=4)
i4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [108]:
i4 = np.eye(4,k=-2)
i4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

# 2D Access

In [110]:
np.random.seed(20)
n68 = np.random.randint(10,80,48).reshape(6,8)
n68

array([[25, 38, 19, 30, 32, 44, 50, 36],
       [26, 72, 26, 17, 16, 36, 23, 68],
       [35, 13, 71, 67, 42, 20, 16, 28],
       [13, 27, 53, 26, 28, 69, 39, 55],
       [16, 73, 34, 28, 43, 52, 13, 28],
       [62, 32, 24, 14, 37, 18, 16, 36]])

In [111]:
n68.shape

(6, 8)

In [112]:
n68[0]

array([25, 38, 19, 30, 32, 44, 50, 36])

In [113]:
n68[-1]

array([62, 32, 24, 14, 37, 18, 16, 36])

In [117]:
n68[3]

numpy.ndarray

In [115]:
n68[3][5]

69

In [116]:
n68[3,5]

69

In [121]:
n68[2:5]

array([[35, 13, 71, 67, 42, 20, 16, 28],
       [13, 27, 53, 26, 28, 69, 39, 55],
       [16, 73, 34, 28, 43, 52, 13, 28]])

In [122]:
n68[2:5,2:7:2]

array([[71, 42, 16],
       [53, 28, 39],
       [34, 43, 13]])

In [123]:
n68[:,3]

array([30, 17, 67, 26, 28, 14])

In [124]:
n68[[2,4,5,3]]

array([[35, 13, 71, 67, 42, 20, 16, 28],
       [16, 73, 34, 28, 43, 52, 13, 28],
       [62, 32, 24, 14, 37, 18, 16, 36],
       [13, 27, 53, 26, 28, 69, 39, 55]])

In [125]:
n68[[2,4,5,3],[1,5,3,7]]  # zip of the vectore used as co-ordinates i.e (2,1),(4,5),(5,3),(3,7)

array([13, 52, 14, 55])

In [126]:
n68

array([[25, 38, 19, 30, 32, 44, 50, 36],
       [26, 72, 26, 17, 16, 36, 23, 68],
       [35, 13, 71, 67, 42, 20, 16, 28],
       [13, 27, 53, 26, 28, 69, 39, 55],
       [16, 73, 34, 28, 43, 52, 13, 28],
       [62, 32, 24, 14, 37, 18, 16, 36]])