In [1]:
import numpy as np

In [6]:
x = np.zeros(20)
x[3] = 5
x

array([0., 0., 0., 5., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [7]:
array_master = np.ones(20)
array_copy = np.copy(array_master)
array_copy

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [9]:
a = np.ones(30) + 100
a

array([101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101., 101., 101., 101.,
       101., 101., 101., 101., 101., 101., 101., 101.])

In [10]:
np.repeat(100,30)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100])

In [18]:
a1 = np.arange(2,11,2)
a2 = np.arange(22,31,2)
a3 = np.vstack((a1,a2))
a3

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [21]:
np.stack((a1,a2),axis = 0)

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [22]:
np.column_stack((a1,a2))

array([[ 2, 22],
       [ 4, 24],
       [ 6, 26],
       [ 8, 28],
       [10, 30]])

In [23]:
np.row_stack((a1,a2))

array([[ 2,  4,  6,  8, 10],
       [22, 24, 26, 28, 30]])

In [28]:
n = np.eye(10)
n[n<1] = 21
n

array([[ 1., 21., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21.,  1., 21., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21.,  1., 21., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21.,  1., 21., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21.,  1., 21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.,  1., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21.,  1., 21., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21.,  1., 21., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21.,  1., 21.],
       [21., 21., 21., 21., 21., 21., 21., 21., 21.,  1.]])

In [29]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])