In [2]:
import numpy as np

In [3]:
#Create an array of range(0,12)
n1=np.arange(12)
n1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# reshape the array 3X4 size

In [10]:
n1 = n1.reshape(3,4)

In [6]:
#Give the dimensions, shape and size of the array

In [12]:
n1.ndim

2

In [17]:
n1.shape

(3, 4)

In [13]:
n1.size

12

In [14]:
print("the number of rows in the array:",n1.shape[0])

the number of rows in the array: 3


In [18]:
print("the number of rows in the array:",len(n1))

the number of rows in the array: 3


In [15]:
print("the number of columns in the array:",n1.shape[1])

the number of columns in the array: 4


In [ ]:
print("the number of rows in the array:",n1.shape[0])

In [19]:
#transpose: fliping rows and columns

In [21]:
n1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
n1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [22]:
len(n1.T)

4

In [23]:
print("the number of columns in the array:",len(n1.T))

the number of rows in the array: 4


In [25]:
print("the number of columns in the array:",n1.size/n1.shape[0])

the number of rows in the array: 4.0


In [31]:
# make an array having 40 elements within the range 35,70 with a size of 5X8

In [32]:
np.arange(35,70).reshape(5,9)

ValueError: cannot reshape array of size 35 into shape (5,9)

In [35]:
np.random.randint(35,70,40).reshape(5,8)

array([[47, 43, 65, 53, 44, 49, 38, 43],
       [47, 61, 47, 48, 63, 53, 57, 43],
       [56, 64, 69, 61, 44, 37, 51, 38],
       [59, 45, 60, 66, 67, 50, 36, 62],
       [64, 48, 67, 46, 51, 68, 37, 36]])

In [37]:
a = np.random.randint(35,70,size=(5,8))

In [ ]:
#print how many unique elements are there in the above array

In [38]:
np.unique(a)

array([35, 37, 40, 41, 44, 46, 48, 49, 50, 51, 53, 54, 57, 58, 59, 60, 61,
       62, 63, 65, 66, 67, 68, 69])

In [39]:
np.unique(a).size

24

In [40]:
len(np.unique(a))

24

In [41]:
np.unique(a).shape[0]

24

In [42]:
#Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [ ]:
# #ouput: array([[100, 110],
#               [120, 130],
#               [140, 150],
#               [160, 170],
#              [180, 190]])

In [43]:
np.arange(100,200,10).reshape(5,2)

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [44]:
np.random.randint(100,200,10)

array([118, 101, 116, 124, 161, 116, 161, 182, 114, 189])

In [46]:
np.arange(100,200,10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

In [48]:
np.arange(100,200,step=10).reshape(5,2)


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [49]:
#Following is the provided numPy array. 
arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])

In [50]:
arr[2]

array([77, 88, 99])

In [ ]:
#return array of items in the third column from all rows

In [68]:
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [51]:
arr[:,2]

array([33, 66, 99])

In [ ]:
#return an item of 2nd row and 3rd column

In [52]:
arr[1,2]

66

In [56]:
#return all the items in the 3rd row, and first two columns

In [58]:
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [59]:
arr[2,0:2]    


array([77, 88])

In [60]:
arr[2,:2]

array([77, 88])

In [61]:
arr[2][:2]

array([77, 88])

In [62]:
arr[2][0:2]

array([77, 88])

In [65]:
arr[2,(0,1)]


array([77, 88])

In [69]:
#return array of following coordinates: (0,2),(1,1),(1,2),(2,1)

In [70]:
arr[[0,1,1,2],[2,1,2,1]]

array([33, 55, 66, 88])

In [ ]:
#Following is the given numpy array return array of odd rows and even columns

In [71]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
#output: [[ 6 12],[30 36],[54 60]]

In [72]:
sampleArray[::2]

array([[ 3,  6,  9, 12],
       [27, 30, 33, 36],
       [51, 54, 57, 60]])

In [73]:
sampleArray[::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [80]:
a =sampleArray[0:6:2,0:4:1]
a
a[0:3:1,1:4:2]


array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [81]:
sampleArray[0:6:2,1:4:2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [82]:
#subtract the following two NumPy arrays and Modify a result array by calculating the square of each element

In [83]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [84]:
result = arrayOne-arrayTwo

In [86]:
result*result

array([[100, 729, 225],
       [289, 121, 676]])

In [87]:
a2=(arrayOne-arrayTwo)**2
a2

array([[100, 729, 225],
       [289, 121, 676]], dtype=int32)

In [88]:
# Return the sum, average, maximum value, minimum value, standard deviation all the numbers greater than 5

In [89]:
n1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [90]:
n1.shape

(3, 4)

In [92]:
a = n1[n1>5]

In [93]:
a

array([ 6,  7,  8,  9, 10, 11])

In [94]:
a.sum()

51

In [95]:
a.mean()

8.5

In [96]:
a.min()

6

In [97]:
a.max()

11

In [98]:
a.std()

1.707825127659933

In [99]:
(n1[n1>5]).sum()

51

In [100]:
(n1[n1>5]).min()

6

In [101]:
sum(n1[n1>5])


51

In [102]:
min((n1[n1>5]))

6

In [103]:
# Given an array of distances: I want to ask the user to enter the start and end location of  his house and 
# the play ground and return all the distances between that range

#then change all those distances to 99

In [105]:
dists = np.random.randint(10,70,20)

In [106]:
#Enter the location of your house and the playground50,60
dists

array([12, 66, 35, 65, 25, 41, 30, 47, 61, 38, 48, 45, 51, 39, 31, 32, 10,
       24, 59, 14])

In [108]:
n = int(input("enter your house location"))
m = int(input('enter your playground location'))
dists[(dists>n) & (dists<m)]

enter your house location30
enter your playground location50


array([35, 41, 47, 38, 48, 45, 39, 31, 32])

In [109]:
dists[(dists>n) & (dists<m)]= 99

In [110]:
dists

array([12, 66, 99, 65, 25, 99, 30, 99, 61, 99, 99, 99, 51, 99, 99, 99, 10,
       24, 59, 14])

In [111]:
# how do I make a 1d array of 15 elements in a 2d array: all the ways

In [3]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [112]:
# Create a 2d array with 1 on the border and 0 inside

In [7]:
n = np.zeros(24).reshape(6,4)
n[0]=1
n[-1]=1
n[:,0] = 1
n[:,-1] = 1
n

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [113]:
#Find non-zero elements from [1,2,0,0,4,0]
#Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
n = np.array([1,2,0,0,4,0])
n[n>0]

array([1, 2, 4])

In [9]:
n = np.array([1,2,0,0,4,0])

array([1, 2, 0, 0, 4, 0])