In [1]:
import numpy as np

In [2]:
n = np.arange(12)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
n = n.reshape(3,4)

In [13]:
n.ndim

2

In [14]:
n.shape

(3, 4)

In [17]:
n.size

12

In [18]:
n

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
n.shape[0]

3

In [20]:
n.shape[1]

4

In [21]:
len(n)

3

In [24]:
len(n.T)

4

In [26]:
n1 = np.random.randint(35,70,(5,9))
n1

array([[61, 44, 52, 60, 61, 69, 47, 56, 39],
       [41, 35, 46, 35, 63, 57, 56, 40, 51],
       [49, 41, 60, 60, 68, 36, 69, 57, 50],
       [68, 60, 58, 41, 51, 40, 49, 45, 69],
       [61, 65, 59, 40, 61, 48, 37, 64, 69]])

In [30]:
n1 = np.arange(100,200,10).reshape(5,2)
n1

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [31]:
arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
arr

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [32]:
arr[2]

array([77, 88, 99])

In [34]:
arr[:,2]

array([33, 66, 99])

In [35]:
arr[1,2]

66

In [36]:
arr[2,:2]

array([77, 88])

In [40]:
arr[[0,1,1,2],[2,1,2,1]]

array([33, 55, 66, 88])

In [41]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [47]:
sampleArray[::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [48]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
(arrayOne-arrayTwo)**2

array([[100, 729, 225],
       [289, 121, 676]], dtype=int32)

In [53]:
n = n[n>5]
n

array([ 6,  7,  8,  9, 10, 11])

In [54]:
sum(n)

51

In [59]:
n.sum()

51

In [60]:
n.mean()

8.5

In [61]:
n.max()

11

In [62]:
n.min()

6

In [63]:
n.std()

1.707825127659933

In [66]:
# Given an array of distances: I want to ask the user to enter the start and end location of  his house and 
# the play ground and return all the distances between that range

#then change all those distances to 99


In [70]:
np.random.seed(10)
dists = np.random.randint(10,70,20)
dists

array([19, 46, 25, 10, 59, 69, 38, 35, 39, 58, 39, 59, 68, 18, 19, 10, 52,
       50, 64, 46])

In [71]:
n = int(input('Enter your location:'))
m = int(input('Enter your playground location'))
print(dists)
dists[(dists>n) & (dists<m)] = 99
print(dists)

Enter your location:30
Enter your playground location50
[19 46 25 10 59 69 38 35 39 58 39 59 68 18 19 10 52 50 64 46]
[19 99 25 10 59 69 99 99 99 58 99 59 68 18 19 10 52 50 64 99]
