In [1]:
import pandas as pd

# Pandas Series

In [2]:
mylist1 = [1,2,3,'a','b','c',4,5]

In [3]:
ps1 = pd.Series(mylist1)
ps1

0    1
1    2
2    3
3    a
4    b
5    c
6    4
7    5
dtype: object

In [4]:
ps2 = pd.Series([100,200,300,400,500],index=['Tata','Birla','Wipro','infy','TCS'],dtype='i4')
ps2

Tata     100
Birla    200
Wipro    300
infy     400
TCS      500
dtype: int32

In [6]:
ps2.index

Index(['Tata', 'Birla', 'Wipro', 'infy', 'TCS'], dtype='object')

In [7]:
ps2.values

array([100, 200, 300, 400, 500], dtype=int64)

In [8]:
type(ps2.values)

numpy.ndarray

In [5]:
ps2.ndim

1

In [6]:
ps2[1]

200

In [7]:
ps2['Wipro']

300

In [8]:
ps2[2:4]

Wipro    300
infy     400
dtype: int32

In [9]:
ps2['Birla' : 'infy']

Birla    200
Wipro    300
infy     400
dtype: int32

In [10]:
ps2[['Birla','Tata','infy']]

Birla    200
Tata     100
infy     400
dtype: int32

In [17]:
ps2[[2,3,1]]

Wipro    300
infy     400
Birla    200
dtype: int64

In [11]:
ps2[ps2>250]

Wipro    300
infy     400
TCS      500
dtype: int32

In [12]:
myd1 = {'TCS':15000,'Infy':20000,'IR':50000}
myd1

{'TCS': 15000, 'Infy': 20000, 'IR': 50000}

In [13]:
ps3 = pd.Series(myd1)
ps3

TCS     15000
Infy    20000
IR      50000
dtype: int64

In [25]:
ps3.index

Index(['TCS', 'Infy', 'IR'], dtype='object')

In [26]:
ps3.keys

<bound method Series.keys of TCS     15000
Infy    20000
IR      50000
dtype: int64>

In [28]:
ps3.values

array([15000, 20000, 50000], dtype=int64)

# DataFrames

In [14]:
myd2 = {'Tata':[100,110,120,130,140],'Birla':[200,210,220,230,240],'Infy':[300,310,320,330,340]}
myd2

{'Tata': [100, 110, 120, 130, 140],
 'Birla': [200, 210, 220, 230, 240],
 'Infy': [300, 310, 320, 330, 340]}

In [15]:
df1 = pd.DataFrame(myd2,index = ['Retail','Transport','IT','Auto','Energy'])
df1

Tata  Birla  Infy
Retail      100    200   300
Transport   110    210   310
IT          120    220   320
Auto        130    230   330
Energy      140    240   340

In [16]:
df1.index

Index(['Retail', 'Transport', 'IT', 'Auto', 'Energy'], dtype='object')

In [17]:
df1.columns

Index(['Tata', 'Birla', 'Infy'], dtype='object')

In [18]:
df1.keys

<bound method NDFrame.keys of            Tata  Birla  Infy
Retail      100    200   300
Transport   110    210   310
IT          120    220   320
Auto        130    230   330
Energy      140    240   340>

# DataFrame Access

In [19]:
df2 = pd.read_csv('D:/Great Learning/Numpy,Pandas,Visualisations/June/3rd June/profit1.csv')
df2

Vol    Rev  Exp Catg  EmpCnt   HQ   Sector
HCL       931  863.5  605  Pub    1935  NCR       IT
MRF       992  821.0  665  Pub    1154  Che     Auto
ISROACL   931  881.6  650  Gov    1361  Blr       RD
Reliance  900  917.0  674  Pub    1443  Mum   Retail
BCCI      925  839.8  615  Pvt     154  Mum   Sports
Birla     900  874.4  676  Pub    1379  Kol   Retail
Flipkart  966  805.0  895  Pvt     119  Blr   Retail
Apollo    966  863.2  608  Pub    1656  Che     Auto
IR        954  733.0  609  Gov   13023  NCR  Service

In [35]:
pwd

'D:\\Great Learning\\Numpy,Pandas,Visualisations\\June\\3rd June'

In [38]:
df2.shape

(9, 7)

In [39]:
df2.index

Index(['HCL', 'MRF', 'ISROACL', 'Reliance', 'BCCI', 'Birla', 'Flipkart',
       'Apollo', 'IR'],
      dtype='object')

In [40]:
df2.columns

Index(['Vol', 'Rev', 'Exp', 'Catg', 'EmpCnt', 'HQ', 'Sector'], dtype='object')

In [41]:
df2.values

array([[931, 863.5, 605, 'Pub', 1935, 'NCR', 'IT'],
       [992, 821.0, 665, 'Pub', 1154, 'Che', 'Auto'],
       [931, 881.6, 650, 'Gov', 1361, 'Blr', 'RD'],
       [900, 917.0, 674, 'Pub', 1443, 'Mum', 'Retail'],
       [925, 839.8, 615, 'Pvt', 154, 'Mum', 'Sports'],
       [900, 874.4, 676, 'Pub', 1379, 'Kol', 'Retail'],
       [966, 805.0, 895, 'Pvt', 119, 'Blr', 'Retail'],
       [966, 863.2, 608, 'Pub', 1656, 'Che', 'Auto'],
       [954, 733.0, 609, 'Gov', 13023, 'NCR', 'Service']], dtype=object)

In [42]:
df2.ndim

2

In [44]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, HCL to IR
Data columns (total 7 columns):
Vol       9 non-null int64
Rev       9 non-null float64
Exp       9 non-null int64
Catg      9 non-null object
EmpCnt    9 non-null int64
HQ        9 non-null object
Sector    9 non-null object
dtypes: float64(1), int64(3), object(3)
memory usage: 576.0+ bytes


In [20]:
df2.describe()

Vol         Rev         Exp        EmpCnt
count    9.000000    9.000000    9.000000      9.000000
mean   940.555556  844.277778  666.333333   2469.333333
std     31.297408   53.389788   90.689029   4006.439036
min    900.000000  733.000000  605.000000    119.000000
25%    925.000000  821.000000  609.000000   1154.000000
50%    931.000000  863.200000  650.000000   1379.000000
75%    966.000000  874.400000  674.000000   1656.000000
max    992.000000  917.000000  895.000000  13023.000000

In [22]:
df2.describe(include='all')

Vol         Rev         Exp Catg        EmpCnt   HQ  Sector
count     9.000000    9.000000    9.000000    9      9.000000    9       9
unique         NaN         NaN         NaN    3           NaN    5       6
top            NaN         NaN         NaN  Pub           NaN  Mum  Retail
freq           NaN         NaN         NaN    5           NaN    2       3
mean    940.555556  844.277778  666.333333  NaN   2469.333333  NaN     NaN
std      31.297408   53.389788   90.689029  NaN   4006.439036  NaN     NaN
min     900.000000  733.000000  605.000000  NaN    119.000000  NaN     NaN
25%     925.000000  821.000000  609.000000  NaN   1154.000000  NaN     NaN
50%     931.000000  863.200000  650.000000  NaN   1379.000000  NaN     NaN
75%     966.000000  874.400000  674.000000  NaN   1656.000000  NaN     NaN
max     992.000000  917.000000  895.000000  NaN  13023.000000  NaN     NaN

In [49]:
df2['Vol']

HCL         931
MRF         992
ISROACL     931
Reliance    900
BCCI        925
Birla       900
Flipkart    966
Apollo      966
IR          954
Name: Vol, dtype: int64

In [50]:
df2.Vol   # not recommended

HCL         931
MRF         992
ISROACL     931
Reliance    900
BCCI        925
Birla       900
Flipkart    966
Apollo      966
IR          954
Name: Vol, dtype: int64

In [51]:
df2['MRF' : 'BCCI']

Vol    Rev  Exp Catg  EmpCnt   HQ  Sector
MRF       992  821.0  665  Pub    1154  Che    Auto
ISROACL   931  881.6  650  Gov    1361  Blr      RD
Reliance  900  917.0  674  Pub    1443  Mum  Retail
BCCI      925  839.8  615  Pvt     154  Mum  Sports

In [27]:
df2['Vol']['MRF']

992

In [28]:
df2.iloc[2:5]

Vol    Rev  Exp Catg  EmpCnt   HQ  Sector
ISROACL   931  881.6  650  Gov    1361  Blr      RD
Reliance  900  917.0  674  Pub    1443  Mum  Retail
BCCI      925  839.8  615  Pvt     154  Mum  Sports

In [29]:
df2.iloc[2:5,3:6]

Catg  EmpCnt   HQ
ISROACL   Gov    1361  Blr
Reliance  Pub    1443  Mum
BCCI      Pvt     154  Mum

In [30]:
df2.iloc[2,::2]

Vol        931
Exp        650
EmpCnt    1361
Sector      RD
Name: ISROACL, dtype: object

In [31]:
df2.iloc[2,[2,5,6]]

Exp       650
HQ        Blr
Sector     RD
Name: ISROACL, dtype: object

In [60]:
df2.iloc[[3,6,4],[1,3,2]]

Rev Catg  Exp
Reliance  917.0  Pub  674
Flipkart  805.0  Pvt  895
BCCI      839.8  Pvt  615

In [63]:
df2.loc[df2['Catg']=='Pub']


Vol    Rev  Exp Catg  EmpCnt   HQ  Sector
HCL       931  863.5  605  Pub    1935  NCR      IT
MRF       992  821.0  665  Pub    1154  Che    Auto
Reliance  900  917.0  674  Pub    1443  Mum  Retail
Birla     900  874.4  676  Pub    1379  Kol  Retail
Apollo    966  863.2  608  Pub    1656  Che    Auto